### ISSUE TITLE
Misspelling in README.md

### ISSUE THREAD

**Issue by ViktorPopp** [cli-stuff/dotload#16]
![image](https://github.com/user-attachments/assets/a28121c6-949a-4883-a9c3-dd163134d61d)

**Comment by okineadev** [comment]
?

**Comment by okineadev** [comment]
> ![image](https://github.com/user-attachments/assets/a28121c6-949a-4883-a9c3-dd163134d61d)
> 

Where is the misspelling??

**Comment by ViktorPopp** [comment]
Recommended

**Comment by okineadev** [comment]
Fixed in https://github.com/cli-stuff/dotload/commit/c58de0a5e69affe607623d132988363c8b3b10e8 👍
